plugins {
    id "java-library"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

dependencies {
    api "org.java-websocket:Java-WebSocket:1.6.0"
    compileOnly "com.google.code.gson:gson:2.14.0"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 25
}
